FROM nginx:latest

FROM nginx:latest

# Copy the static Nginx configuration
COPY nginx.conf /etc/nginx/nginx.conf

# Copy static frontend files
COPY client/dist /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]