FROM nginx:latest
COPY nginx.conf /etc/nginx/nginx.conf
COPY client/dist /usr/share/nginx/html
EXPOSE 80
CMD ["sh", "-c", "envsubst '\$API_HOST' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && sleep 30 && nginx -g 'daemon off;'"]
