events {}
http {
  server {
    listen 80;
    server_name localhost; # Render updates to your domain or onrender.com URL

    # Serve Vite client
    location / {
      root /usr/share/nginx/html;
      try_files $uri $uri/ /index.html; # Supports Vite SPA routing
    }

    # Proxy API requests
    location /api/ {
      proxy_pass http://okanban-api:3000; # Internal Render service name
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}