events {}

http {
  resolver 10.0.0.2 valid=10s ipv6=off;
  resolver_timeout 20s;

  upstream api_backend {
    server http://okanban-api-tnt9:10000 max_fails=5 fail_timeout=20s;
  }

  server {
    listen 80;
    server_name localhost;

    location /health {
      proxy_pass http://api_backend/health;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
      root /usr/share/nginx/html;
      try_files $uri $uri/ /index.html;
    }

    location /api/ {
      proxy_pass http://api_backend;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_connect_timeout 20s;
      proxy_read_timeout 20s;
      proxy_send_timeout 20s;
    }
  }
}