databases:
  - name: okanban-db-managed
    databaseName: okanban
    user: okanban
    region: oregon

services:
  - type: web
    name: okanban-api
    runtime: image
    plan: free
    region: oregon
    image:
      url: docker.io/lukevideo/okanban-api:latest
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: okanban-db-managed
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: DEBUG
        value: sequelize:*,okanban:db
    startCommand: node index.js

  - type: web
    name: okanban-nginx
    runtime: image
    plan: free
    region: oregon
    image:
      url: docker.io/lukevideo/okanban-nginx:latest
    healthCheckPath: /
    envVars:
      - key: NGINX_PORT
        value: 80
      - key: API_HOST
        value: okanban-api-tnt9.onrender.com