# On part d'une image existante
FROM postgres:16

# Repertoire de travail dans le conteneur
WORKDIR /etc/postgresql


# Ajout des scripts d'initialisation
# @see: https://hub.docker.com/_/postgres
COPY ./data/create_tables.sql /docker-entrypoint-initdb.d/create_table.sql

# Documenter le port 5432 du conteneur 
EXPOSE 5432